### PR TITLE
Update for Flarum beta 8

### PR DESCRIPTION
**Pull request by dsevillamartin**

### CODE REVIEW

**Comment by Ralkage** [comment]
@datitisev I'll give a crack at it later today, preferably with a local beta-8/hacked-together version of dev-master.

**Comment by Ralkage** [comment]
We are good money 💰 @datitisev I got the hackaboo beta 8 core working locally (through blood, sweat, and tears ofc) and the generator gave me no problem in whipping up a new extension,

**Comment by dsevillamartin** [comment]
@Ralkage Core is still going to have extension changes, though, so the beta 8 generator isn't finalized.

**Comment by Ralkage** [comment]
@datitisev do you want to open a part two of the next changes?

**Comment by dsevillamartin** [comment]
@Ralkage There was a reason why this PR was kept open 😛. My bad, next time I'll label it WIP.

**Comment by Ralkage** [comment]
Done goofed, addressed in #9 as WIP, reverted merge via #8.

**Pull request merged**
